### ISSUE TITLE
enhancement: multiple domain infrastructure

### ISSUE THREAD

**Issue by osnet** [mlan/docker-postfix-amavis#1]
Hey guy : ), 

i was wondering if it would be possible to pass an array of domains via .env to this image ?
would be a nice feature

**Comment by mlan** [comment]
Hi again @osnet. :smiley:

In [incoming-destination-domain](https://github.com/mlan/docker-postfix-amavis#incoming-destination-domain) multiple domains are mentioned. Is this what you are thinking of?

If you have an example at hand it would perhaps help me understand your idea better?

**Comment by osnet** [comment]
i was thinking of a chance to set an array for mta domains in the env file

in my case something like
pwr-srv.net, power-server.at, oberland-it.net

the server then should be able to recieve and send mails to and from these domains.

must be possible somehow 🤪

**Comment by mlan** [comment]
OK. Sounds reasonable.

But perhaps it is already possible? Try by putting the following in your `.env` file:

```bash
MAIL_DOMAIN="pwr-srv.net power-server.at oberland-it.net"
```

And in the `docker-compose.yml` you include:

```yml
  mta:
    environment:
      - MAIL_DOMAIN=${MAIL_DOMAIN}
```

Please let me know it goes.

**Comment by osnet** [comment]
meh,

I have tried it ...  but with no luck.
i had to edit  mta/etc/postfix/main.cf  manually as well

```
virtual_mailbox_domains = $mydomain   -> virtual_mailbox_domains = tld1 tld2
```

working as expected now... 

MAYBE there is an issue with my volumes. gonna check it on another host xD

**Comment by mlan** [comment]
Hi again,

Please forgive me if this is already obvious, but I just want to make sure. In [Configuration / seeding procedure](https://github.com/mlan/docker-postfix-amavis#configuration--seeding-procedure) it is mentioned that "The seeding procedure will leave any existing configuration untouched." You can use `FORCE_CONFIG` to override this behavior. 

In [10-postfix-common](https://github.com/mlan/docker-postfix-amavis/blob/master/src/postfix/entry.d/10-postfix-common#L52) the virtual domains should be setup (for virgin installs).

**Comment by osnet** [comment]
writing  ```FORCE_CONFIG=```  to the .env file right ?
nope no changes, ok i can live with that, just document it and adapt when needed ...

**Comment by mlan** [comment]
Perhaps you need it in the `docker-compose.yml` file? 

There should be an entry in the container log indicating how the configuration is handled. Most of the time you should expect this line: 
```bash
docker-entrypoint.sh[1] NOTE: No unlock file found, so not touching configuration.
```

**Comment by osnet** [comment]
found it
``` Oct 27 15:03:41 docker-entrypoint.sh[1] NOTE: No unlock file found, so not touching configuration. ```

tried:
```    
    environment:
      - FORCE_CONFIG=
```
> nope

tried in .env

> nope


am i missing something, mmh

**Comment by osnet** [comment]
i found an workaround ... 
i just mounted an  empty file 

```
./mta.unlock:/srv/etc/.docker.unlock:ro
```

and theeeen : 

```

mta_1  | Oct 27 20:28:53 docker-entrypoint.sh[1] NOTE: Configuring amavis for domains pwr-srv.net emsters.de kreidebleich.net
mta_1  | Oct 27 20:28:53 docker-entrypoint.sh[1] NOTE: Setting dkim selector and domain to default and pwr-srv.net

```
works : ))

**Comment by mlan** [comment]
Hi @osnet 

yes, I can see that what you suggest works as a workaround, but it feels a bit clunky. In [Configuration / seeding procedure](https://github.com/mlan/docker-postfix-amavis#configuration--seeding-procedure) it is mentioned that "you can override the default behavior by setting `FORCE_CONFIG` to a _no-empty_ string." So perhaps you need to have:

```yml
    environment:
      - FORCE_CONFIG=OVERRIDE
```

Separately. I get a feeling that you want to use ` FORCE_CONFIG` each time the container is started. So I assume you want your configuration defined in the `docker-compose.yml` and `.env` files and _not_ in the postfix configuration files on the persistent volume. I designed the configuration procedure with the opposite priority in mind. Use the definition on the persistent volume and _only_ for virgin container creation use what is provided in the `docker-compose.yml` and `.env` files. I love to hear from you which approach you prefer and why that is so.
