### ISSUE TITLE
request: integrate fetchmail

### ISSUE THREAD

**Issue by mailschranz** [mlan/docker-postfix-amavis#11]
Hello, I would like to fetch mails from other POP accounts with fetchmail. Would it be possible to integrate fetchmail into the full image?

Many Thanks

**Comment by mlan** [comment]
amavis is getting difficult to support, so I'm about to retire this image. I suggest these images instead:
[mlan/postfix](https://github.com/mlan/docker-postfix)
[mlan/rspamd](https://github.com/mlan/docker-rspamd)
