### ISSUE TITLE
Build from Docker file, unrar or /etc/amavisd.conf missing

### ISSUE THREAD

**Issue by posixPilot** [mlan/docker-postfix-amavis#12]
Hi,

I'm trying to cross build docker-postfix-amavis on the armv7 architecture, but I'm running into a bit of a problem.  I'm kind of new to this, so hopefully I'm not making a simple mistake.

I using 'docker buildx' on a Mac to build the armv7 target from your GitHub source.  Building with the default Dockerfile ends with a message about the missing unrar package in Alpine Linux.  A bit of research led me to discover that  unrar was moved to another repository in 3.15.

To address this I set REL=3.14, where the unrar package was available.  Building this image results in a complaint about the amavisd.conf file:

`#10 23.05 mv: can't rename '/etc/amavisd.conf': No such file or directory`

I suspect that the location of the Amavis config changed between 3.14 and 3.15.  So, I went back to REL=latest and commented out the 'unrar' dependency.  This allows the build to complete, but I'm unsure what the lack of the unrar package might break (ClamAV seems a logical candidate).

Is there a better way to fix this?  I understand that unrar moved to a 'non-free' repo, but I've been unable to find how one would access this repo in Alpha Linux.

Any help would be appreciated.

  Thanks
  Mike

**Comment by mlan** [comment]
amavis is getting difficult to support, so I'm about to retire this image. I suggest these images instead:
[mlan/postfix](https://github.com/mlan/docker-postfix)
[mlan/rspamd](https://github.com/mlan/docker-rspamd)
