### ISSUE TITLE
missing .env variables

### ISSUE THREAD

**Issue by osnet** [mlan/docker-postfix-amavis#2]
demo or not, please modify the delivered .env file
there are missing some vars 

```
      - MESSAGE_SIZE_LIMIT .......
      - SMTP_RELAY_HOSTAUTH=${SMTP_RELAY_HOSTAUTH-}
      - SMTP_TLS_SECURITY_LEVEL=${SMTP_TLS_SECURITY_LEVEL-}
      - SMTP_TLS_WRAPPERMODE=${SMTP_TLS_WRAPPERMODE-no}
```

```
WARNING: The MESSAGE_SIZE_LIMIT variable is not set. Defaulting to a blank string.
WARNING: The SMTP_RELAY_HOSTAUTH variable is not set. Defaulting to a blank string.
WARNING: The SMTP_TLS_SECURITY_LEVEL variable is not set. Defaulting to a blank string.
WARNING: The SMTP_TLS_WRAPPERMODE variable is not set. Defaulting to a blank string.
```

my .env  now 

``` 
[..]
# 50MB
MESSAGE_SIZE_LIMIT=52428800         

# not needed :) 
SMTP_RELAY_HOSTAUTH=no                  

# none,encrypt,secure,fingerprint
SMTP_TLS_SECURITY_LEVEL=none         

# if yes, requires "smtp_tls_security_level = encrypt or stronger.
SMTP_TLS_WRAPPERMODE=no                
[..]
```

**Comment by osnet** [comment]
WTF ... 
is setting  hostauth to everything differnt than  "no" postfix  expands the main.cf with some values  never to be reverted if not mapped external : )) 

just in case you did a typo or misconfigured the hostauth you got  

```
relayhost= xxxx
smtp_sasl_auth_enable = yes
smtp_sasl_password_maps = hash:/etc/postfix/smtp_authen
smtp_sasl_security_options = noanonymous

```
in your config, no chance to get rid of it exept  editing directly ...

**Comment by mlan** [comment]
Hi @osnet 

I have not seen the warnings before:
```bash
WARNING: The MESSAGE_SIZE_LIMIT variable is not set. Defaulting to a blank string.
WARNING: The SMTP_RELAY_HOSTAUTH variable is not set. Defaulting to a blank string.
WARNING: The SMTP_TLS_SECURITY_LEVEL variable is not set. Defaulting to a blank string.
WARNING: The SMTP_TLS_WRAPPERMODE variable is not set. Defaulting to a blank string.
```
When are they generated? When you type:
```bash
docker-compose config
```
I have only tested the demo files on Linux/bash systems. I think you mentioned you use XCP-ng where perhaps the `${VARIABLE-default_value_if_variable_not_defined}` construct does not work? If so, then you need to use another method, perhaps like the one you suggest.

**Comment by mlan** [comment]
On the second topic.

The configuration procedure treat `SMTP_RELAY_HOSTAUTH` in a special way, which is briefly discussed here: [`SMTP_RELAY_HOSTAUTH`](https://github.com/mlan/docker-postfix-amavis#smtp_relay_hostauth).

If you don't use a relay or use a relay which does not require authentication you should set `SMTP_RELAY_HOSTAUTH=`, that is an empty string.

**Comment by osnet** [comment]
` I think you mentioned you use XCP-ng `
xcp-ng  is an opensource fork of citrix xen-server 
docker hosts are running as HVM on this .
i'm using  centos 7 as long as docker cant be used on centos8 without reconfiguring the network stuff : )

**Comment by mlan** [comment]
OK. I will try to find some time to test the demo on a centos7 host. Do you know where you see the warnings?
