### ISSUE TITLE
make postfix accessable from the WAN

### ISSUE THREAD

**Issue by osnet** [mlan/docker-postfix-amavis#3]
hi, 

i have been trying a lot but did not come to any solution ... 
accessing the smtp within my /22 subnet  is  quite fine. 
i can login and send 
But accessing the postfix from outside is giving me an 4.7.1  relay acces denied ... 

i have edited the main.cf  the master.cf with several attemts. no luck.
how to make this postfix great again ? : P

**Comment by osnet** [comment]
mh ok i added 
```
mynetworks = 192.0.0.0/8

smtpd_client_restrictions =
  permit_mynetworks
``` 
 this may help for my clients in lan wifi an vpn 
mmh  but cell phones  might struggle : )

the auth against kopano ldap should be implemented as well  if  using  imap smtp  from the outside ^^

**Comment by osnet** [comment]
YAY found an solution ^^ 
apk add cyrus-sasl  ... 
...rebuilding the dockerimage : )

**Comment by mlan** [comment]
hello @osnet 

I have a feeling you are talking about setting up an open SMTP relay on port 25, is that so? The `mlan/postfix-amavis` image is specifically designed _not_ to allow unauthenticated clients to submit messages. The client credentials are providede using `SMTPD_SASL_CLIENTAUTH="client1:{plain}passwd1 client2:{plain}passwd2"` see, [Incoming SMTPS and submission client authentication](https://github.com/mlan/docker-postfix-amavis#incoming-smtps-and-submission-client-authentication).

**Comment by osnet** [comment]
mmh not exactly ... 
to authenticate against ldap configured on only ONE server  you need to pass authentication requests from smtp forward to imap via  rimap mechanism on saslauthd. 
this is not possible in you setup  out of the box : )

**Comment by mlan** [comment]
OK I see. So you are describing a setup where kopano is not involved (directly), yes?

**Comment by osnet** [comment]
kopano is in this case just the permission broker. 
smtp -> rimap-> kopano-gateway (imap) -> ldap
but to realize this some additional packages like  cyrus-sasl  are required. they are not  build in

**Comment by mlan** [comment]
Hi @osnet 

I am preparing a release where both LDAP and RIMAP SMTPS SASL are easy to set up using envvars. It is based on Dovecot (and not Cyrus) since it much better maintained and feature rich.

**Comment by mlan** [comment]
Added support for configuring LDAP and RIMAP SMTPS SASL using envvars, based on Dovecot in 4822bce0c3775c51ddb73ff4177773fe6d44e17e.
