### ISSUE TITLE
add possibility in .env for  delimiter

### ISSUE THREAD

**Issue by osnet** [mlan/docker-postfix-amavis#4]
one should be able - in case needed - to configure the delimiter option of postfix and dovecot.

i.e.
```
MAIL_DELIMITER="+-"
```

-> mta/etc/postfix/main.cf add to bottom OR change default
```
recipient_delimiter = +-
```

-> mta/etc/dovecot/dovecot.conf  add to bottom
```
recipient_delimiter = +-
```

**Comment by mlan** [comment]
Hi @osnet 

I can see how `/etc/postfix/address_extension` containing
```
/([^+]+)[+-].*@(.+)/    $1@$2
```
and issuing 
```bash
postmap /etc/postfix/address_extension
postconf virtual_alias_maps="<other alias maps>, regexp:/etc/postfix/address_extension"
```
will allow email addresses like `user+info@domain.com` to be forwarded to `user@domain.com`.

The email `user+info@domain.com` will be delivered to the _Inbox_ of the user `user`. But not to any sub-folder. Was this what you had in mind?

**Comment by osnet** [comment]
user-*
user+*
> user

subfolder rules are upon the client/user himself

i need both - and +

my email „accounts“ to register somewhere are
i.e.
master-spotify@
master-twitter@

gitlab uses + for subadressing

**Comment by mlan** [comment]
OK. Many thanks for sharing this. I will consider implementing a simple way to set this up.

**Comment by mlan** [comment]
Added support for `REGEX_ALIAS` in 4822bce0c3775c51ddb73ff4177773fe6d44e17e. Mark as closed.

**Comment by osnet** [comment]
works like a charm
