### ISSUE TITLE
environment docker-compose

### ISSUE THREAD

**Issue by osnet** [mlan/docker-postfix-amavis#5]
HI, 
if you auth against AD / Samba  the userattrributes are expanding
if one has mail@bla.com AND  mail@fu.net  ...  the mail addrs not being standard are stored in    ``otherMailbox``

In this case you have to adjust the docker compose file in the mta section 

from
```
- LDAP_QUERY_FILTER_USER=(&(objectclass=${LDAP_USEROBJ})(kopanoAccount=1)(mail=%s))
```

to
```
- LDAP_QUERY_FILTER_USER=(&(objectclass=${LDAP_USEROBJ})(kopanoAccount=1)(mail=%s)(otherMailbox=%s))
```

otherwise postfix wont deliver

**Comment by mlan** [comment]
@osnet 

Many thanks for sharing this very useful information. I will consider including it in the section [LDAP mailbox lookup](https://github.com/mlan/docker-postfix-amavis#ldap-mailbox-lookup) of the documentation.

**Comment by mlan** [comment]
Hi @osnet 

Perhaps the [`LDAP_QUERY_FILTER_ALIAS`](https://github.com/mlan/docker-postfix-amavis#ldap_query_filter_alias) environment variable can be useful in this scenario too?
