### ISSUE TITLE
deliver alias to malibox part #2 : )

### ISSUE THREAD

**Issue by osnet** [mlan/docker-postfix-amavis#7]
Hi fan, 

i have had an interesting dive thru tons of  opstfix howtos and potential threats to life : )) 

i am now able to deliver mails to user, user%extension, alias of user , alias ofuser%extension
the main thing is to let postfix lookup ldap aswell 

here are the main points of  main.cf

```
# Mail directory
virtual_transport = lmtp:192.168.220.4:2003
virtual_mailbox_domains = hash:/etc/postfix/virtual-domains
virtual_alias_maps = ldap:/etc/postfix/ldap-aliases.cf regexp:/etc/postfix/address_extension
virtual_mailbox_maps = ldap:/etc/postfix/ldap-users.cf
```

ldap-users.cf
```
start_tls = no
server_host = ldaps://SERVER:636
search_base = CN=Users,DC=mail,DC=net
version = 3
bind = yes
bind_dn = CN=ldapbind,CN=Users,DC=mail,DC=net
bind_pw = redacted
scope = sub
query_filter = (&(objectClass=user)(mail=%s))
result_attribute = mail

```

ldap-aliases.cf
```
start_tls = no
server_host = ldaps://SERVER:636
search_base = CN=Users,DC=mail,DC=net
version = 3
bind = yes
bind_dn = CN=ldapbind,CN=Users,DC=mail,DC=net
bind_pw = redacted
scope = sub
query_filter = (&(objectClass=user)(otherMailbox=%s))
result_attribute = mail
```

as u know i have an standalone postfix  but stuff is the same ...  
dependency  ``yum install postfix-ldap``

example:

my user  -  domain : ceo@mail.net   -> works
i have an alias like master-chief :  master-chief@mail.net  <-> ceo@mail.net -> works
AND 
with our regex for delimiters ( + - )    i can add an extrastring  with  + - to  master-chief like  master-chief-justice
i am able to recieve

a little hint   recieving  fom  apple , gmail  outlook  etc works  fine. 
sending  from an  other kopano host not.  mmh  perhaps my fault somewhere : )

**Comment by osnet** [comment]
i found the solution why kopanoA  not sending mails correctly to kopanoB 
in the mta config we have setup 

```
virtual_alias_maps = $virtual_ldap_alias_maps $virtual_regexp_alias_maps
transport_maps = hash:/etc/postfix/transport
virtual_ldap_alias_maps = 
virtual_regexp_alias_maps = regexp:/etc/postfix/regexp-aliases

```

all fun and games, BUT with this setup  sending from  kopano A to kopano B with mail ``test-user@mail.net`` 
gets trimmed by regex to  ``test@mail.net`` so i disabled it 

```
virtual_alias_maps = $virtual_ldap_alias_maps $virtual_regexp_alias_maps
transport_maps = hash:/etc/postfix/transport
virtual_ldap_alias_maps = 
virtual_regexp_alias_maps = 
#regexp:/etc/postfix/regexp-aliases
```

now sending works better : )

**Comment by mlan** [comment]
Hi @osnet

Again many thanks for sharing your insights with us.

I believe that the [mlan/postfix-amavis](https://github.com/mlan/docker-postfix-amavis) image can offer this functionality by using the [`LDAP_QUERY_FILTER_ALIAS`](https://github.com/mlan/docker-postfix-amavis#ldap_query_filter_alias) environment variable.

When using LDAP entries like this:

```yml
dn: uid=demo,ou=users,dc=example,dc=com
cn: demo
objectClass: top
objectClass: inetOrgPerson
objectClass: kopano-user
sn: demo
uid: demo
mail: demo@example.com
telephoneNumber: 0123 123456789
title: First User
kopanoAccount: 1
kopanoAliases: trial@example.com
kopanoEnabledFeatures: imap
kopanoEnabledFeatures: pop3
```

And while initiating [mlan/postfix-amavis](https://github.com/mlan/docker-postfix-amavis) with:

```sh
LDAP_QUERY_FILTER_ALIAS=(&(kopanoAccount=1)(kopanoAliases=%s))
```

Mail to `demo@example.com` and `trial@example.com` are both delivered to the mailbox of user `demo`.

**Comment by osnet** [comment]
ja, close it. 
works perfekt
