### ISSUE TITLE
MAIL_ALIASES not working correctly

### ISSUE THREAD

**Issue by stefangries** [mlan/docker-postfix-amavis#8]
When setting the MAIL_ALIASES env variable, to
`test@xxxxxx.de:stefan@xxxxxx.de`
it results in the virt-aliases file beeing set to 
`test@xxxxxx.de: stefan@xxxxxx.de`
The log indicates, that this is a wrong format:
`postmap: warning: /etc/postfix/virt-aliases, line 1: record is in "key: value" format; is this an alias file?`
The correct format is without the colon:
`test@xxxxxx.de stefan@xxxxxx.de`
If you change this manually in the file (remove the colon) and run postmap again, the redirection works.

**Comment by mlan** [comment]
Hi @stefangries 

Many thanks for reporting this bug. I will release a new version that will fix it shortly.

**Comment by stefangries** [comment]
Good to hear! Thank you very much. I will test immediately after release :-)

**Comment by mlan** [comment]
Hi @stefangries 

This should be fixed in ded9e9fc04bbac50d7b14103e41e4648ea03b48b. 
Love to hear back from you.

**Comment by stefangries** [comment]
Thank you very much, it works! 

But there is a small bug. When I set force_config=1 to transfer MAIL_ALIASES to virt-aliases, the virt-aliases file is not emptied first. I.e. the MAIL_ALIASES are only appended to virt-aliases. In my case there were still the erroneous entries with colon in it, which I removed by hand.

If I have several entries in MAIL_ALIASES and I remove one of them, this entry is not removed from virt-aliases either.

**Comment by mlan** [comment]
Many thanks for reporting this. There appears to be an inconsistency on how `FORCE_CONFIG` works. Will put that under review.

**Comment by mlan** [comment]
@stefangries 

In cc926ca29a5cb10b69ea4b01ef02210d8754be19 the behavior was changed so that old `MAIL_DOMAIN`, `MAIL_BOXES` and `MAIL_ALIASES` entries is backed up and cleared when issuing `FORCE_CONFIG`.

**Comment by stefangries** [comment]
Great, working perfectly!

**Comment by mlan** [comment]
Phew, finally. 😃 
Closing this now.
