### ISSUE TITLE
Hardening

### ISSUE THREAD

**Issue by losintikfos** [mlan/docker-postfix-amavis#9]
I was proposing we add below settings to ensure further hardening, do you have any objections?
Also do you think OpenSRSd is  required for forwarding?
```
#
# Postscreen
#
postscreen_greet_action = enforce
postscreen_dnsbl_threshold = 3
postscreen_dnsbl_action = enforce
postscreen_dnsbl_sites =
   zen.spamhaus.org*3
   bl.spameatingmonkey.net*2
   bl.spamcop.net
   dnsbl.sorbs.net
   b.barracudacentral.org=127.0.0.[2..11]*2

# 
# Error response codes
#
invalid_hostname_reject_code = 554
multi_recipient_bounce_reject_code = 554
non_fqdn_reject_code = 554
unknown_address_reject_code = 554
unknown_client_reject_code = 554
unknown_hostname_reject_code = 554
unknown_local_recipient_reject_code = 554
unknown_relay_recipient_reject_code = 554
unknown_virtual_alias_reject_code = 554
unknown_virtual_mailbox_reject_code = 554
unverified_recipient_reject_code = 554
unverified_sender_reject_code = 554
```

Further 
```
smtpd_helo_required = yes
smtpd_delay_reject = yes
smtpd_helo_restrictions = 
    permit_mynetworks, 
    reject_invalid_helo_hostname,
    reject_unknown_helo_hostname, 
    permit

smtpd_relay_restrictions = 
    permit_mynetworks, 
    permit_sasl_authenticated,
    reject_unauth_destination

smtpd_recipient_restrictions = 
    reject_invalid_helo_hostname,
    reject_non_fqdn_helo_hostname, 
    reject_invalid_hostname,
    reject_non_fqdn_recipient,
    reject_unlisted_recipient,
    reject_unknown_sender_domain,
    reject_unknown_recipient_domain,
    reject_unauth_pipelining,
    permit_mynetworks,
    permit_sasl_authenticated,
    reject_unauth_destination,
    reject_rbl_client multi.uribl.com,
    reject_rbl_client dsn.rfc-ignorant.org,
    reject_rbl_client dul.dnsbl.sorbs.net,
    reject_rbl_client list.dsbl.org,
    reject_rbl_client sbl-xbl.spamhaus.org,
    reject_rbl_client bl.spamcop.net,
    reject_rbl_client dnsbl.sorbs.net,
    reject_rbl_client cbl.abuseat.org,
    reject_rbl_client ix.dnsbl.manitu.net,
    reject_rbl_client combined.rbl.msrbl.net,
    reject_rbl_client rabl.nuclearelephant.com,
    reject_rbl_client zen.spamhaus.org, 
    reject_rhsbl_reverse_client dbl.spamhaus.org,
    reject_rhsbl_helo dbl.spamhaus.org,
    reject_rhsbl_sender dbl.spamhaus.org,
    permit

smtpd_client_restrictions = 
    reject_sender_login_mismatch,
    reject_non_fqdn_sender,
    reject_unlisted_sender,
    permit_mynetworks, 
    permit_sasl_authenticated, 
    reject_unauth_destination, 
    reject_invalid_hostname,
    reject_unknown_sender_domain,
    reject_unauth_pipelining

smtpd_sender_restrictions = 
    reject_sender_login_mismatch,
    reject_non_fqdn_sender,
    reject_unlisted_sender,
    permit_mynetworks,
    permit_sasl_authenticated,
    reject_unauth_destination,
    reject_invalid_hostname,
    reject_unknown_sender_domain,
    reject_unauth_pipelining
```

**Comment by mlan** [comment]
Hello @losintikfos 

Many thanks for a very interesting and relevant post.

Initially I have some general comments. These parameters can already be set using environment variables both on command line and in a `docker-compose.yml` file. And, of cause, directly in the `/etc/postfix/main.cf` within the container. So are you suggesting these parameters should be hard coded in this repository? If so, it would be helpful if you can offer compelling arguments for doing so.

You mention `opensrsd`, but I suppose `postsrsd` offer the same functionality? You are welcome to elaborate on a user case where srs come into play.

**Comment by losintikfos** [comment]
@mlan I am aware you can override `/etc/postfix/main.cf` using possible mapped volume file and indeed directly from container. I am also aware you have enabled `smtpd_relay_restrictions=permit_sasl_authenticated,reject`. 

I was thinking we enhance the settings using propose to ensure they are enabled by default. Or maybe have them as optional environmental variable say `POSTFIX_ADDITIONAL_CNF=/some/location/my-hardening.cnf`, which means existing settings are left intact, yet giving users freedom to override and/or add additional settings in their own discretion. Please correct me if something like this or similar already exist :)

I believe `opensrsd` and `postsrsd` offer the same functionality indeed, I was suggesting we add this to give alias forwarding to be handled appropriately to say gmail or similar servers, without mails been flagged as spams. Again correct me if this facility is already been handled by existing setup or similar.

Thanks

**Comment by mlan** [comment]
Hi @losintikfos 

In addition to the methods you describe above there is the possibility to initiate the configuration using environment variables, for details please see, [Environment variables](https://github.com/mlan/docker-postfix-amavis#environment-variables).

To exemplify: 

```sh
SMTPD_HELO_REQUIRED=yes
SMTPD_DELAY_REJECT=yes
SMTPD_HELO_RESTRICTIONS=permit_mynetworks,reject_invalid_helo_hostname,reject_unknown_helo_hostname,permit
```

In your post you are suggesting another mechanism, but perhaps keeping the parameters in a `docker-compose.yml` file will result in a similar workflow?

My comments above is in no way intended to diminish the value of your insights. As a minimum I propose that we place your text in the wiki here on github.

To help me continue study your suggestion, is there any of the parameters that you describe above that you believe are more of universal value than the other ones?

**Comment by losintikfos** [comment]
Hi @mlan 

Thanks for the pointers. Following your response, it is clear the suggestion to extend on the settings or provide a facility to make it easy for users to expand on their settings already exist. I notice within the sources a function to convert service settings from environmental variables enabled for all stack services. I must admit this is awesome - great work.

I was thinking maybe an integration of `postsrsd` to offer optional forwarding rewrite to avoid receiving servers flagging the message as spam. That said, I am sure one can easily add `postsrsd` container service integration without any issue.

Thanks

**Comment by mlan** [comment]
Hi @losintikfos 

I will certainly consider integrating `postsrsd`.
